AllCops:
  Exclude:
    - '*.gemspec'

Style/Documentation:
  Enabled: false
Style/EachWithObject:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/AbcSize:
  Max: 20

Metrics/MethodLength:
  Max: 20

Metrics/LineLength:
  Max: 100
