AllCops:
  Exclude:
    - 'bin/*'
    - '*.gemspec'
    - 'lib/terjira/ext/**/*'
    - 'Rakefile'

Style/Documentation:
  Enabled: false
Style/EachWithObject:
  Enabled: false
Style/RescueModifier:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false
Lint/Eval:
  Enabled: false
Lint/ImplicitStringConcatenation:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/AbcSize:
  Max: 20

Metrics/MethodLength:
  Max: 30

Metrics/LineLength:
  Max: 100
