language: ruby

addons:
  code_climate:
    repo_token: 98123461fbec752591c40e3e7af46bcdc6576723bfac2d89c084bfae989e4db3

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.10
  - 2.2.0
  - 2.3.0

before_install:
  - gem install i18n --no-rdoc --no-ri --no-document

script: bundle exec rspec spec/

after_success:
  - bundle exec codeclimate-test-reporter
