language: ruby

addons:
  code_climate:
    repo_token: 98123461fbec752591c40e3e7af46bcdc6576723bfac2d89c084bfae989e4db3

rvm:
  - 2.4
  - 2.5
  - 2.6

before_install:
  - gem install i18n --no-document

script: bundle exec rspec spec/

after_success:
  - bundle exec codeclimate-test-reporter
